name: Only test

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  run-all-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup maven
        uses: stCarolas/setup-maven@4.5
        with:
          maven-version: 3.8.2

      - name: All the test and Coverage Checks
        run: mvn clean install